name: kuama_flutter
description: A new Flutter project.
version: 0.2.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

# DATA

  dio: ^4.0.6
  shared_preferences: ^2.0.15

  permission_handler_platform_interface: ^3.9.0
  geolocator_platform_interface: ^4.0.5

# DOMAIN

## Data extensions
  meta:
  pure_extensions: ^4.2.0
  rxdart: ^0.27.4

## Primitive data
  tuple: ^2.0.0
  built_value: ^8.4.0
  built_collection: ^5.1.1
  equatable: ^2.0.3

## Functionality
  convert: ^3.1.0
  get_it: ^7.2.0
  synchronized: ^3.0.0+2

# PRESENTATION

  provider: ^6.0.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_lints: ^2.0.1

  test: ^1.21.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

  # To generate .g files:
  # flutter pub run build_runner build --delete-conflicting-outputs
  # flutter pub run build_runner watch --delete-conflicting-outputs
  # The version depends on the packages that use it
  build_runner: ^2.3.0

flutter:


# To generate index files: flutter pub run index_generator:main
index_generator:
  exclude:
    # Ignore all generated dart files
    - '**.g.dart'
    # Ignore all private folders or files
    - '{_,**/_}*{/**,.dart}'
  indexes:
    - path: lib
      name: kuama_flutter
      library: kuama_flutter
      include:
        - 'src/shared/**'
      exports:
        - package: built_collection/built_collection
        - package: tuple/tuple
          show: [Tuple2, Tuple3, Tuple4, Tuple5]
        - package: equatable/equatable
        - package: get_it/get_it
        - package: rxdart/rxdart

    - path: lib
      name: app_pages
      library: kuama_flutter_app_pages
      include:
        - 'src/features/app_pages/**'
    - path: lib
      name: dio
      library: kuama_flutter_dio
      include:
        - 'src/features/dio/**'
    - path: lib
      name: permissions
      library: kuama_flutter_permissions
      include:
        - 'src/features/permissions/**'
    - path: lib
      name: positioner
      library: kuama_flutter_positioner
      include:
        - 'src/features/positioner/**'