name: kuama_flutter
description: A new Flutter project.
# version: 1.0.0
# homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

# DATA

  dio: ^4.0.0
  shared_preferences: ^2.0.0

  permission_handler_platform_interface: ^3.6.0
  geolocator_platform_interface: ^2.3.2

# DOMAIN

## Data extensions
  meta:
  pure_extensions: ^3.4.0
  rxdart: ^0.27.0

## Primitive data
  dartz: ^0.10.0
  built_value: ^8.1.0
  built_collection: ^5.1.0
  equatable: ^2.0.0

## Functionality
  convert: ^3.0.0
  get_it: ^7.2.0
  synchronized: ^3.0.0

# PRESENTATION

  provider: ^6.0.0
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  mockito: ^5.0.15
  remove_from_coverage: ^2.0.0

  # To generate .g files:
  # flutter pub run build_runner build --delete-conflicting-outputs
  # flutter pub run build_runner watch --delete-conflicting-outputs
  # The version depends on the packages that use it
  build_runner: ^2.1.2
  index_generator: ^2.0.3
  flutter_lints: ^1.0.4

flutter:


# To generate index files: flutter pub run index_generator:main
index_generator:
  filters:
    # Ignore all private folders or files
    - black: .*\/_.*\/.*
    - black: .*\/_.*.dart*
  indexes:
    - path: lib
      name: kuama_flutter
      library: kuama_flutter
      export:
        - src/shared
    - path: lib
      name: app_pages
      library: kuama_flutter_app_pages
      export:
        - src/features/app_pages
    - path: lib
      name: dio
      library: kuama_flutter_dio
      export:
        - src/features/dio
    - path: lib
      name: permissions
      library: kuama_flutter_permissions
      export:
        - src/features/permissions
    - path: lib
      name: positioner
      library: kuama_flutter_positioner
      export:
        - src/features/positioner