name: Test
on:
  pull_request:
    # Some filters on when this actions should run on pull requests
    # https://frontside.com/blog/2020-05-26-github-actions-pull_request/#:~:text=When%20a%20Github%20Actions%20workflow,opened%20%2C%20synchronize%20%2C%20and%20reopened%20.&text=Basic%20pull_request%20usage.
    types: [ ready_for_review, review_requested, synchronize ]
  push:
    branches:
      # Run test, analyze and coverage generation also when the PR gets merged into develop
      - develop
jobs:
  test:
    #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: ubuntu-latest
    #sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/cache@v1
        with:
          path: ./.dart_tool
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.5.x'
      - run: flutter pub get
      # generate dart mocks files
      - run: flutter packages pub run build_runner build --build-filter="test/**"
      # run static analysis code
      - run: flutter analyze --no-fatal-infos
      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage
      # Upload coverage reports to Codecov
      # https://github.com/marketplace/actions/codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info